name: Update douban data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1,9 * * *"
    - cron: "0 4 * * *"
    - cron: "0 6 * * *"
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  process:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      USER: ${{ github.repository_owner }}
      REPO_NAME: ${{ secrets.REPO_CINE }}
      SRC_NAME: source

    steps:
      - uses: actions/checkout@v4

      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.REPO_NAME }}
          token: ${{ secrets.GH_TOKEN_ACCESS }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run script page
        if: github.event.schedule == '0 4 * * *'
        run: |
          pushd ${SRC_NAME} &&
          bash scripts/run-douban.sh data-pages &&
          popd

      - name: Run script hot
        if: github.event.schedule == '0 6 * * *'
        run: |
          pushd ${SRC_NAME} &&
          bash scripts/run-douban.sh data-hot &&
          popd

      - name: Run script rank
        if: github.event.schedule == '0 2 * * *'
        run: |
          pushd ${SRC_NAME} &&
          bash scripts/run-douban.sh data-rank &&
          popd

      - name: Run script top
        # if: github.event.schedule == '0 1,9 * * *'
        run: |
          pushd ${SRC_NAME} &&
          bash scripts/run-douban.sh data-top &&
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
          # commit_options: '--no-verify --signoff'
          push_options: "--force"
          file_pattern: "data-*/*"
