name: sync data

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 5 * * *"
    - cron: "8 18 * * *"
    - cron: "10 10 * * *"

jobs:
  process:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      USER: hantang
      SRC_NAME: cinephile-code

    steps:
      - uses: actions/checkout@v4

      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.SRC_NAME }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # - name: Set up committer
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: List script
        run: |
          pushd ${{ env.SRC_NAME }} && 
          ls -al && ls -l scripts-douban/run-daily.sh &&
          popd

      - name: Run script top
        if: github.event.schedule == '5 5 * * *'
        run: |
          pushd ${{ env.SRC_NAME }} && 
          bash scripts-douban/run-daily.sh data-top &&
          popd

      - name: Run script page
        if: github.event.schedule == '10 10 * * *'
        run: |
          pushd ${{ env.SRC_NAME }} && 
          bash scripts-douban/run-daily.sh data-pages &&
          popd

      - name: Run script hot
        if: github.event.schedule == '8 18 * * *'
        run: |
          pushd ${{ env.SRC_NAME }} && 
          bash scripts-douban/run-daily.sh data-hot &&
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update by github action
          # commit_options: '--no-verify --signoff'
          push_options: "--force"
          file_pattern: "data-*/*"
